name: DadJokes
main: de.slevermann.minecraft.dadjokes.DadJokePlugin
version: 1.0.0

commands:
  dadjoke:
    description: Dad joke for everyone on the server
    usage: /dadjoke
    aliases:
      - flachwitz